name: DAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Start JSON Server (API)
        run: |
          npx json-server --watch ./src/db/db.json --port 3000 &
          sleep 10

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk -t owasp/zap2docker-stable \
            zap-baseline.py -t http://host.docker.internal:3000 \
            -r zap-report.html || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
